// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwcgufoffpkgynpcxvdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3Y2d1Zm9mZnBrZ3lucGN4dmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzAzNDksImV4cCI6MjA1ODUwNjM0OX0.G0PNg27G3K4O7gqpCt9XLSJhmsSn6Cjcomj6QtbZE_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);