
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

// Default to empty strings to prevent crashes during development or testing
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://qwcgufoffpkgynpcxvdl.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3Y2d1Zm9mZnBrZ3lucGN4dmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzE5MzMsImV4cCI6MjA2MTI0NzkzM30.rcwkcECf8dhXG3yokmj-LG9dHnjGO9nysAfV9qe5jQw';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'supabase.auth.token',
  },
});
